### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by JouBqa** [majikayogames/SimpleDungeons#3]
Can you do a video tutorial showing how to add this to our own project? I don't understand how to use it

**Comment by majikayogames** [comment]
Hey :) yes I am planning to do a tutorial on this & expanding it with some more quality of life features built in. I have some other videos I am working on first but that is on my to do list. I think I responded on your YouTube comment, but you can generate in editor with the force generate in editor checkbox if you want to save a specific layout. For spawning the player in the level, that would probably involve putting a script to do so on something like the EntranceRoom, and then setting the minimum and maximum spawns of EntranceRoom both to 1 to force it to spawn only 1. That way, the player can be spawned in via the script on that room once it is placed.

**Comment by majikayogames** [comment]
https://www.youtube.com/watch?v=v58l05FsdPs Tutorial is out as well as some more info on how to spawn the player in at 39:40 in the video.
