### ISSUE TITLE
Rooms from DungeonKit do not rotate during generation

### ISSUE THREAD

**Issue by SlimFishyy** [majikayogames/SimpleDungeons#4]
Every room is placed with the same rotation as it's in DungeonKit scene. The solution I'm using so far is duplicating a room 4 times with different rotation. Rotating entire room node causes problems with door positions, so I currently manually rotate meshes and change the size of AABB with this tool:

```
func rotate_room(value) -> void:
	for child in get_children():
		if child.name != "AABB":
			child.rotation = child.rotation + Vector3(0,PI/2,0)
		else:
			var temp_size : Vector3 = child.size
			child.size.x = temp_size.z
			child.size.z = temp_size.x
```

But that's a hacky solution and It would be better if there was an option for room rotation in geneator and it would place a room and randomly rotate it.

**Comment by majikayogames** [comment]
Yep this is on my todo list to add actually so I'll leave this issue here. ETA one month because I have to finish an FPS tutorial first. Going to add a few features and try to get SimpleDungeons to a 'v1' state as now it has some hacky parts and is in need of some more features.

**Comment by majikayogames** [comment]
Implemented in v2!
