### ISSUE TITLE
Compatible with MultiplayerSpawner?

### ISSUE THREAD

**Issue by argentlynx** [majikayogames/SimpleDungeons#7]
If I pregen the map onready, my server successfully adds it to the level node, and the multiplayerspawner sends it to all clients.

However, if I then remove all the rooms: clients don't remove rooms.  If I then re-generate, clients also don't get new rooms.

Probably is just me not doing something right with the config of multiplayerspawner for these scenes (rooms) but thought I'd check if I'm missing something simple.  Thanks

I'm following this godot tutorial on multiplayer https://godotengine.org/article/multiplayer-in-godot-4-0-scene-replication/

**Comment by majikayogames** [comment]
This would be out of scope, if you want to add or remove removes, you'll have to trigger the same function calls such as generate() a second time on each client, at the same time. Or, create your room nodes with multiplayer replication in mind. After all, the rooms are just Node3Ds which inherit the DungeonRoom3D type. You can place some multiplayer synchronization on that. If you are removing rooms, it might be easier to just do something like having an RPC honestly. The MultiplayerSpawner etc are not super hackable to allow for something like this, so I don't even know if it would be possible.

It MIGHT work currently if you just use the RoomContainer as a MultiplayerSpawner's node path, and only generate on the server.

Either way, I think this would require a custom solution that does not extend easily in a way I could think to have it generalize to how the add-on is currently set up.
