### ISSUE TITLE
【Feature Request】Add map for Navigation

### ISSUE THREAD

**Issue by SugarWong97** [majikayogames/SimpleDungeons#8]
Hi,

Is any possible to add a small map as UI to show player's location in the Dungeons ? 

Thanks for your great work.

**Comment by majikayogames** [comment]
This would be out of scope for this add-on. If you want to do this, I would recommend doing something like, querying the DungeonGenerator3D using [get_room_at_pos](https://github.com/majikayogames/SimpleDungeons/wiki#get_room_at_posgrid_pos--vector3i---dungeonroom3d) to check the occupied spaces on a grid floor, and display a map of your own based on that.
